apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-cryptomarket-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-cryptomarket-exporter
      app.kubernetes.io/name: prometheus-cryptomarket-exporter
      app.kubernetes.io/part-of: prometheus-cryptomarket-exporter
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
